version: '3'
services:
  frontend:
    image: svelte-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5173
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.ts
      - ./svelte.config.js:/app/svelte.config.js

  gotenberg:
    image: gotenberg/gotenberg:7
    environment:
      - LOG_LEVEL=DEBUG
    ports:
      - "3000:3000"

  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
